### ISSUE TITLE
USER STORY 1 <Love Running Poll>

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/My-First-Agile-Project#7]
In order to select an option, as a user I can select an option from the poll.

## Acceptance Criteria

* Options should be displayed as a list.
* Options should be selectable with a checkbox next to the option list item.
* Font should be size 10
  
## Tasks
  
 - [ ] Create an unordered list of options
 - [ ] Add a checkbox next to each option
 - [ ] Set font size to size 10
