### ISSUE TITLE
USER STORY 2 <Love Running>

### ISSUE THREAD

**Issue by cornishcoder1** [cornishcoder1/My-First-Agile-Project#8]
In order to **automatically hide the poll** as **adminstrator**, I can **choose an expiry date for poll.**

## Acceptance Criteria

* The poll should close at 11.59pm on the chosen expiry date.
* A placeholder should show when the poll was displayed, with text that says 'new poll coming soon'.
* The admin expiry date should be 3 days after the chosen expiry date. 
  
## Tasks
  
 - [ ] Update admin module view to include date picker (HTML & CSS).
 - [ ] Update website view with placeholder 'new poll coming soon'.
 - [ ] Create Javascript function to validate expiry date is at least after 3 days. 
 - [ ] Create a job to check expired polls everyday at 11.59pm and hide them.
 - [ ] Test functionality.
